# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8adf08dd7214b44351cd55ac1b1dda0778034e703b4bb25f8a89c86728d43a6ffd78677791d6889bdc92527bec074ff006fae28f552a616e7d61dc4eb7e33f38

test:
  secret_key_base: 62358b69f4d7d7b90ad1cac031bca1f85e87f74dbe9639c3fc493f8a12375d25a2b7444804b950db23c71995d0abdb0ae6793ff7dc60d60b56e33e53baf55b59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
